[project]
name = "django-admin"
version = "0.1.0"
description = "RBAC permission management system"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.16",
    "django-redis>=7.0.0",
    "djangorestframework>=3.17.1",
    "djangorestframework-simplejwt>=5.5.1",
    "djangorestframework-stubs>=3.17.1",
    "drf-spectacular>=0.30.0",
    "jinja2>=3.1.6",
    "mysqlclient>=2.2.8",
    "openpyxl>=3.1.5",
    "psutil>=7.2.2",
    "requests>=2.34.2",
    "user-agents>=2.2.0",
]
