# Generated by Django 6.0.7 on 2026-08-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatortemplate',
            name='app_label',
            field=models.CharField(blank=True, help_text='所属应用，如 system', max_length=64, null=True, verbose_name='所属应用'),
        ),
        migrations.AddField(
            model_name='generatortemplate',
            name='model_name',
            field=models.CharField(blank=True, help_text='模型名称，如 Post', max_length=64, null=True, verbose_name='模型名称'),
        ),
    ]
