# Generated by Django 6.0.7 on 2026-08-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_fix_permission_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatortemplate',
            name='has_backend',
            field=models.BooleanField(default=False, help_text='是否已经落地后端（数据表 + 接口）', verbose_name='是否已生成后端'),
        ),
        migrations.AddField(
            model_name='generatortemplate',
            name='is_new_table',
            field=models.BooleanField(default=False, help_text='开启时不依赖已有模型，按字段配置直接建表', verbose_name='是否新建数据表'),
        ),
    ]
