# Generated by Django 6.0.7 on 2026-08-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_backfill_and_seed_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('belong_dept', models.IntegerField(blank=True, help_text='数据归属部门', null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('title', models.CharField(blank=True, help_text='标题', max_length=255, null=True, verbose_name='标题')),
                ('content', models.TextField(blank=True, help_text='内容', null=True, verbose_name='内容')),
                ('status', models.BooleanField(default=False, help_text='状态', verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, default=0, help_text='排序', null=True, verbose_name='排序')),
            ],
            options={
                'verbose_name': '公告管理',
                'verbose_name_plural': '公告管理',
                'db_table': 'system_notice',
                'ordering': ('-create_datetime',),
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='users',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='apiwhitelist',
            name='method',
            field=models.IntegerField(blank=True, default=None, help_text='接口请求方法', null=True, verbose_name='接口请求方法'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='value',
            field=models.JSONField(blank=True, help_text='值', null=True, verbose_name='值'),
        ),
    ]
