# Generated by Django 6.0.7 on 2026-08-17 21:36

import apps.file.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.FileField(help_text='文件地址', max_length=255, upload_to=apps.file.models.media_file_name, verbose_name='文件地址'),
        ),
    ]
